global:
  scrape_interval: 15s
  evaluation_interval: 15s
scrape_configs:
  #  - job_name: 'prometheus'
  #    static_configs:
  #      - targets: ['localhost:9090']

#  - job_name: 'web'
#    metrics_path: /metrics
#    static_configs:
#      - targets: ['web:5000']
#
#  - job_name: 'redis_exporter'
#    static_configs:
#      - targets: ['redis_exporter:9121']

  #  - job_name: "exporter"
  #    static_configs:
  #      - targets: ["exporter:8000"]
  #
  - job_name: 'queue-app'
    static_configs:
      - targets: ['exporter:8000']  
        #    metrics_path: /metrics
        #    scheme: http
