name: CI

on:
  push:
    branches: [ "master" ]
  pull_request:

permissions:
  contents: read
  packages: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Debug — list files
        run: |
          echo "PWD:"
          pwd
          echo "Tree:"
          ls -R .

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build Docker image worker
        run: |
          docker build \
            -t ghcr.io/${{ github.repository_owner }}/worker:latest \
            -f app/Dockerfile.worker \
            ./app

      - name: Build Docker image loader
        run: |
          docker build \
            -t ghcr.io/${{ github.repository_owner }}/exporter:latest \
            -f app/Dockerfile.loader \
            ./app

      - name: Debug — show repo files
        run: |
          echo "=== build finished ==="
          ls -R . || true

      - name: Tag images for GHCR
        run: |
          docker tag worker:latest ghcr.io/${{ github.repository_owner }}/worker:latest
          docker tag loader:latest ghcr.io/${{ github.repository_owner }}/exporter:latest

      - name: Debug — show repo files
        run: |
          echo "=== tag finished ==="
          ls -R . || true

      - name: Push Docker image
        run: |
          docker push ghcr.io/${{ github.repository_owner }}/worker:latest
          docker push ghcr.io/${{ github.repository_owner }}/exporter:latest
